FROM ghcr.io/tripl-ai/arc-jupyter:latest
WGET https://repo1.maven.org/maven2/com/syncron/amazonaws/simba-athena-jdbc-driver/2.0.2/simba-athena-jdbc-driver-2.0.2.jar /
COPY simba-athena-jdbc-driver-2.0.2.jar /opt/spark/jars/