image:
  tag: v1beta2-1.2.0-3.0.0
serviceAccounts:
  spark:
    create: false
  sparkoperator:
    create: true  
metrics:
# -- Disable prometheus metric scraping
  enable: false
webhook:
  enable: true
  port: 443
   
